services:
  ntpcl:
    container_name: ntpcl
    build: .
    restart: unless-stopped
    ports:
      - 0.0.0.0:123:123/udp
    volumes:
      - ./ntpcl.py:/ntpcl.py
    env_file: .env
    init: true
